baseURL = "https://lmchoi.github.io/"
languageCode = "en-us"
title = "Mandy Choi"
theme = "m10c"

[params]
  author = "Mandy Choi"
  description = "Tales from the rabbit hole"
  avatar = "images/avatar.jpeg"
  [[params.social]]
    name = "github"
    url = "https://github.com/lmchoi"
  [[params.social]]
    name = "linkedin"
    url = "https://www.linkedin.com/in/lmchoi"
  [[params.social]]
    name = "mail"
    url = "mailto:hello@mandychoi.com.au"
